### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by z3t0** [joshfinnie/archey-osx#10]
I was wondering if there were any possible optimizations to make this faster?

**Comment by ChainsawBaby** [comment]
I don't think there's much that can be done to improve the speed. As it's execution time already is 350ms

**Comment by z3t0** [comment]
@ChainsawBaby Oh, how can I got about measuring execution time? The reason I ask is that it seems to take a while longer on my machine

**Comment by ChainsawBaby** [comment]
Just run the `time` and the path for the archey command
Like mine: `time /usr/local/bin/archey -c`

Or do you mean when you open a new terminal session?

**Comment by z3t0** [comment]
Yeah okay, it seems it only takes about 330ms on mine haha... I must just be getting impatient. Sorry for wasting your time.

**Comment by ChainsawBaby** [comment]
Heh, no worries.
Don't forget to close the issue
